package org.prog.homeworks.session2;

import java.util.Objects;

//TODO: add air company and flight number
//TODO: add hash code and equals that will compare company name and flight number
//TODO: add overload flyTo: destination, startAriport, transitAirport and print:
// Flight (flightNumber) of comapny (comapny) from to through
public class Airplane {

    private String CompanyName;
    private int FlightNumber;

    public Airplane() {
    }

    public Airplane(String companyName, int flightNumber) {
        CompanyName = companyName;
        FlightNumber = flightNumber;
    }

    public String getCompanyName() {
        return CompanyName;
    }

    public void setCompanyName(String companyName) {
        CompanyName = companyName;
    }

    public int getFlightNumber() {
        return FlightNumber;
    }

    public void setFlightNumber(int flightNumber) {
        FlightNumber = flightNumber;
    }

    //empty flyTo method without additional parameters
    public void flyTo() {
        if (this.FlightNumber == 0 && this.CompanyName == null) {
            System.out.println("No fly info!");
        } else {
            System.out.println("Flight " + this.FlightNumber + " of comapny " + this.CompanyName);
        }
    }

    //flyTo method without transitAirport parameters
    public void flyTo(String destination, String startAriport) {
        if (this.FlightNumber == 0 && this.CompanyName == null) {
            System.out.println("No info about FlightNumber and CompanyName\n" +
                      "Fly from " + startAriport + " to " + destination);
        } else {
            System.out.println("Flight " + this.FlightNumber + " of comapny " + this.CompanyName
                    + " from " + startAriport + " to " + destination);
        }
    }


    //flyTo method with all parameters
    public void flyTo(String destination, String startAriport,
                      String transitAirport) {
        if (this.FlightNumber == 0 && this.CompanyName == null) {
            System.out.println("No info about FlightNumber and CompanyName\n"
                    + "Fly from " + startAriport + " to " + destination + " through "
                    + transitAirport);
        } else {
            System.out.println("Flight " + this.FlightNumber + " of comapny " + this.CompanyName
                    + " from " + startAriport + " to " + destination + " through "
                    + transitAirport);
        }
    }

    //equals and hashcode methods i have generated by IntelligentIdeas standart tool
    @Override
    public boolean equals(Object object) {
        if (this == object) return true;
        if (object == null || getClass() != object.getClass()) return false;
        Airplane airplane = (Airplane) object;
        return FlightNumber == airplane.FlightNumber && Objects.equals(CompanyName, airplane.CompanyName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(CompanyName, FlightNumber);
    }
}
